#!/bin/bash
set -euo pipefail

# Pins face-auth to one specific physical camera, closing the "plug in a USB device that
# claims the real camera's VID/PID and feeds it replayed/synthetic frames" injection vector.
#
# VID/PID alone doesn't identify hardware — it's just a string the device reports, and any USB
# device can claim someone else's. What can't be spoofed without physically tampering with the
# machine's internals is the USB port chain a device is wired to. This script reads that from
# sysfs, writes a udev rule that only creates /dev/face-auth-ir for a device at that exact port
# (down to the specific V4L2 function index, since some cameras expose more than one node —
# capture and metadata — at the same port), and records the same identity in face-auth.toml so
# face-auth itself re-checks it on every authenticate/enroll call, independent of the udev rule.
#
# Run this once, after confirming (e.g. via a successful face-enroll) which device is actually
# the right camera. Re-run it if you intentionally replace the hardware.

CONFIG_FILE="/etc/face-auth.toml"
UDEV_RULE="/etc/udev/rules.d/99-face-auth-camera.rules"
SYMLINK_NAME="face-auth-ir"

if [ "$EUID" -ne 0 ]; then
    echo "Must run as root: sudo ./pin-camera.sh [/dev/videoN]"
    exit 1
fi

DEVICE="${1:-}"
if [ -z "$DEVICE" ] && [ -f "$CONFIG_FILE" ]; then
    DEVICE=$(grep -E '^device\s*=' "$CONFIG_FILE" | sed -E 's/^device\s*=\s*"(.*)"\s*$/\1/' || true)
fi
if [ -z "$DEVICE" ]; then
    echo "Usage: sudo ./pin-camera.sh /dev/videoN"
    echo "(no device given, and none configured in $CONFIG_FILE — enroll first with an"
    echo " explicit --device, or pass the device path here)"
    exit 1
fi

REAL_DEVICE=$(readlink -f "$DEVICE" 2>/dev/null || true)
if [ -z "$REAL_DEVICE" ] || [ ! -e "$REAL_DEVICE" ]; then
    echo "Error: $DEVICE does not resolve to an existing device"
    exit 1
fi
KERNEL_NAME=$(basename "$REAL_DEVICE")
SYSFS_NODE="/sys/class/video4linux/$KERNEL_NAME"
if [ ! -d "$SYSFS_NODE" ]; then
    echo "Error: $SYSFS_NODE not found — is $DEVICE a V4L2 device?"
    exit 1
fi

BUS_PATH=$(readlink -f "$SYSFS_NODE/device")
INDEX=$(cat "$SYSFS_NODE/index")
ID_PATH=$(udevadm info --query=property --path="/class/video4linux/$KERNEL_NAME" 2>/dev/null | grep '^ID_PATH=' | cut -d= -f2-)
if [ -z "$ID_PATH" ]; then
    echo "Error: could not determine ID_PATH for $DEVICE via udevadm"
    exit 1
fi

echo "Pinning $DEVICE ($KERNEL_NAME):"
echo "  bus path : $BUS_PATH"
echo "  index    : $INDEX"
echo "  ID_PATH  : $ID_PATH"
echo

cat > "$UDEV_RULE" <<EOF
# Generated by pin-camera.sh — do not hand-edit, re-run pin-camera.sh instead.
# Only creates /dev/$SYMLINK_NAME for a V4L2 node at this exact physical USB port and
# function index, so re-enumeration across boots (or a device plugged in elsewhere claiming
# the same VID/PID) does not get picked up under this name.
SUBSYSTEM=="video4linux", ENV{ID_PATH}=="$ID_PATH", ATTR{index}=="$INDEX", SYMLINK+="$SYMLINK_NAME"
EOF

udevadm control --reload-rules
udevadm trigger --subsystem-match=video4linux
sleep 1

if [ ! -e "/dev/$SYMLINK_NAME" ]; then
    echo "Error: /dev/$SYMLINK_NAME did not appear after reloading udev rules."
    echo "Check $UDEV_RULE and 'udevadm info -a $DEVICE'."
    exit 1
fi
echo "/dev/$SYMLINK_NAME -> $(readlink -f /dev/$SYMLINK_NAME)"

# A `#`-prefixed line makes TOML treat everything after it — including any text `>>` happens
# to concatenate onto it — as part of that same comment, silently swallowing whatever we meant
# to append instead of erroring. Append only ever lands cleanly on its own line if the file
# already ends in a newline, so this is checked before every append rather than assumed.
ensure_trailing_newline() {
    if [ -s "$CONFIG_FILE" ] && [ "$(tail -c1 "$CONFIG_FILE" | wc -l)" -eq 0 ]; then
        echo >> "$CONFIG_FILE"
    fi
}

set_config_string() {
    local key="$1" value="$2"
    if grep -q "^${key}\s*=" "$CONFIG_FILE"; then
        sed -i "s|^${key}\s*=.*|${key} = \"${value}\"|" "$CONFIG_FILE"
    elif grep -q "^# ${key} = " "$CONFIG_FILE"; then
        sed -i "s|^# ${key} = .*|${key} = \"${value}\"|" "$CONFIG_FILE"
    else
        ensure_trailing_newline
        echo "${key} = \"${value}\"" >> "$CONFIG_FILE"
    fi
}

set_config_number() {
    local key="$1" value="$2"
    if grep -q "^${key}\s*=" "$CONFIG_FILE"; then
        sed -i "s|^${key}\s*=.*|${key} = ${value}|" "$CONFIG_FILE"
    elif grep -q "^# ${key} = " "$CONFIG_FILE"; then
        sed -i "s|^# ${key} = .*|${key} = ${value}|" "$CONFIG_FILE"
    else
        ensure_trailing_newline
        echo "${key} = ${value}" >> "$CONFIG_FILE"
    fi
}

echo "Updating $CONFIG_FILE..."
set_config_string "device" "/dev/$SYMLINK_NAME"
set_config_string "pinned_camera_path" "$BUS_PATH"
set_config_number "pinned_camera_index" "$INDEX"

echo ""
echo "=== Camera pinned ==="
echo "face-auth will now refuse to authenticate or enroll if the device at /dev/$SYMLINK_NAME"
echo "doesn't match this exact physical port and function index."
echo ""
echo "This closes the frame-injection vector (a spoofed USB device impersonating the real"
echo "camera's VID/PID). It does not by itself defend against presentation attacks (a photo"
echo "or screen held up to the real, legitimate camera) — that's what the motion-based"
echo "liveness check during authenticate_scan is for. See README.md's Security & Limitations"
echo "section."
