[package]
name = "face-enroll"
version = "0.1.0"
edition = "2021"
license.workspace = true
publish.workspace = true

[[bin]]
name = "vinoauthface"
path = "src/main.rs"

[dependencies]
face-auth-core = { path = "../face-auth-core" }
anyhow = { workspace = true }
clap = { workspace = true }
clap_complete = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
libc = "0.2"
sha2 = "0.10"

[features]
npu = ["face-auth-core/npu"]
