[package]
name = "face-camera-diag"
version = "0.1.0"
edition = "2021"
license.workspace = true
publish.workspace = true

[[bin]]
name = "vinoauthface-camera-diag"
path = "src/main.rs"

[dependencies]
face-auth-core = { path = "../face-auth-core" }
clap = { workspace = true }
anyhow = { workspace = true }

[features]
npu = ["face-auth-core/npu"]
