[package]
name = "face-auth-core"
version = "0.1.0"
edition = "2021"
license.workspace = true
publish.workspace = true

[dependencies]
tract-onnx = { workspace = true }
tract-core = { version = "0.23", package = "tract-core" }
image = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
config = { workspace = true }
dirs = { workspace = true }
byteorder = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

serde = { version = "1.0", features = ["derive"] }
toml = "1.1"
nix = { version = "0.31", features = ["fs"] }
libc = "0.2"
openvino = { workspace = true, optional = true }

[features]
npu = ["dep:openvino"]
